// <auto-generated />
using Document_Service.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DocumentService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240407060928_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Document_Service.Models.Abiturient", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("text");

                    b.Property<string>("accessToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Abiturients");
                });

            modelBuilder.Entity("Document_Service.Models.EducationDocument", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("text");

                    b.Property<string>("date")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("documentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("grade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Educations");
                });

            modelBuilder.Entity("Document_Service.Models.PassportDocument", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("text");

                    b.Property<string>("date")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("series")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Passports");
                });

            modelBuilder.Entity("Document_Service.Models.ScanDocument", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("text");

                    b.Property<byte[]>("educationFile")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("passportFile")
                        .HasColumnType("bytea");

                    b.HasKey("id");

                    b.ToTable("Scans");
                });

            modelBuilder.Entity("Document_Service.Models.EducationDocument", b =>
                {
                    b.HasOne("Document_Service.Models.Abiturient", "abiturient")
                        .WithOne("educationDocument")
                        .HasForeignKey("Document_Service.Models.EducationDocument", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("abiturient");
                });

            modelBuilder.Entity("Document_Service.Models.PassportDocument", b =>
                {
                    b.HasOne("Document_Service.Models.Abiturient", "abiturient")
                        .WithOne("passportDocument")
                        .HasForeignKey("Document_Service.Models.PassportDocument", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("abiturient");
                });

            modelBuilder.Entity("Document_Service.Models.ScanDocument", b =>
                {
                    b.HasOne("Document_Service.Models.Abiturient", "abiturient")
                        .WithOne("scanDocument")
                        .HasForeignKey("Document_Service.Models.ScanDocument", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("abiturient");
                });

            modelBuilder.Entity("Document_Service.Models.Abiturient", b =>
                {
                    b.Navigation("educationDocument")
                        .IsRequired();

                    b.Navigation("passportDocument")
                        .IsRequired();

                    b.Navigation("scanDocument")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
